language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran
install:
  # You may want to periodically update this, although the conda update
  # conda line below will keep everything up-to-date.  We do this
  # conditionally because it saves us some downloading if the version is
  # the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no 
  - conda config --add channels pyne
  - conda config --add channels cyclus
  - conda update -q conda
  - conda install conda-build jinja2 setuptools binstar patchelf nose
  # Useful for debugging any issues with conda
  - conda info -a
  
  # download CI repo
  - wget https://github.com/pyne/pyne-ci/archive/master.zip -O pyne-ci.zip
  - unzip -j pyne-ci.zip "*/pyne/*" -d conda-recipe
  
  # Replace dep1 dep2 ... with your dependencies
  #- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION dep1 dep2 ...
  #- source activate test-environment
  - conda build --no-test conda-recipe
  - conda install pyne --use-local

script:
  - cd tests
  #- nosetests
  - ./travis-run-tests.sh

  # Build the pyne-amalgamation test program 
  - git clone https://github.com/pyne/pyne-amalgamation.git
  - cd ..
  - python amalgamate.py
  - mv pyne.h pyne.cpp tests/pyne-amalgamation
  - cd tests
  - BASE=/home/travis/miniconda make -C pyne-amalgamation


